export var TOUR_DB =
[
  { name:'Users Current Location'           , lat:0        , long: 0          , picture: require('./Photos/stops/langson.png'), desc:'',            },  //00
  //Shirby
  { name:'Cross Cultural Center'            , lat:33.653283, long: -117.743652, picture: require('./Photos/stops/langson.png'), desc:'The Cross Cultural Center is a space for students to imagine and inspire an equitable and socially just campus, to affirm and develop intersectional and cultural identities, and to build a more inclusive community. With plenty of space for students to meet and host club events, the Cross Cultural Center is constantly a hub for diverse experiences.',},  //01
  { name:'Aldrich Hall'                     , lat:33.648461, long: -117.840436, picture: require('./Photos/stops/langson.png'), desc:'Aldrich Hall is a central University Administration building containing not only graduate and undergraduate admissions, but also the University Registrar. You can also find the Chancellors Office in Aldrich Hall!',},  //02
  { name:'Langson Library'                  , lat:33.647067, long: -117.841051, picture: require('./Photos/stops/langson.png'), desc:'Langson Library is one of the eight original buildings on campus, designed by architect William Pereira in 1965. The library is a great resource for research in a wide variety of subjects, along with plenty of study spaces and printing for students.',},  //03
  { name:'Engineering Hall'                 , lat:33.643583, long: -117.841422, picture: require('./Photos/stops/langson.png'), desc:'Engineering Hall is the newest engineering building on the UC Irvine campus, with a spacious 350-seat auditorium for students. Additionally, it houses the Department of Electrical Engineering and Computer Science, as well as faculty offices and administrative offices. It is commonly known as the "nice glass building in Engineering".',},  //04
  { name:'Physical Science Classroom'       , lat:33.643492, long: -117.842575, picture: require('./Photos/stops/langson.png'), desc:'Physical Science Classroom is a smart classroom located right next to Physical Sciences Lecture Hall and often confused with the larger lecture hall.',},  //05
 //Calvin
  { name:'Ayala Science Library'            , lat:33.649421, long: -117.844023, picture: require('./Photos/stops/langson.png'), desc:'Ayala Science Library is one of the largest consolidated science, technology, and medicine libraries in the nation. It contains the collections and services that support research and teaching in the schools of Biological Sciences, Engineering, Information and Computer Science, Physical Sciences, portions of social Ecology, and Medicine.',},  //06
  { name:'Berk Hall Nursing Science'        , lat:33.64656 , long: -117.856254, picture: require('./Photos/stops/langson.png'), desc:'Berk Hall Nursing Science is the room that belongs to Nursing Science Student Affairs and Support Services that provides information and resource services for prospective, current and past students. They offer both graduate and undergraduate students with admissions advising and academic advising as well as course planning.',},  //07
  { name:'Humanities Gateway'               , lat:33.648227, long: -117.84443 , picture: require('./Photos/stops/langson.png'), desc:'Humanities Gateway is home to the Office of the Dean, Humanities Commons, the Samuel Jordan Center for Persian Studies and Culture, and the departments of Film and Media, Art History, Asian American Studies, African American Studies, and Gender and Sexuality Studies.  A fun fact about this structure is that it was designed with green technologies in mind, and was the first LEED Platinum building on the UCI campus.',},  //08
  { name:'Claire Trevor Theatre'            , lat:33.650742, long: -117.846335, picture: require('./Photos/stops/langson.png'), desc:'Claire Trevor Theatre is home to the many forms of art such as plays, dances, and performances. It was originally known as the Village Theatre but the edifice was renovated thanks to a generous contribution by Academy Award winning actress Claire Trevor and renamed in her honor when the updates were completed. Today, the proscenium theatre is our largest on-campus venue with seating for almost 300 persons.',},  //09
  { name:'Mesa Court'                       , lat:33.652979, long: -117.845317, picture: require('./Photos/stops/langson.png'), desc:'Mesa Court is a first-year housing community with 32 classic halls that range in size from 48-85 bed spaces, and three new towers, each housing 306 students. Classic halls offer single, double and triple occupancy rooms. The Mesa Court Towers offer quad occupancy rooms. Each hall contains a theme such as art, music, technology, sustainability issues, community service, leadership and as well as general interest.',},  //10
  //Kimberly
  { name:'Bren Events Center'               , lat:33.649411, long: -117.846964, description:"The Bren Events Center is home to a wide variety of events from sporting events to musical performance to exhibitions and much more. It provides exciting entertainment to thousands of fans each year. "},  //11
  { name:'Arroyo Vista'                     , lat:33.646854, long: -117.829043, description:"Arroyo Vista (commonly referred to as AV) is a theme sponsored housing community that provides homes to undergraduates and transfer students. Each house has 16 to 34 residents living in double occupancy rooms. Academic, special theme houses and greek themed homes can be found in Arroyo Vista."},  //12
  { name:'Vista Del Campo'                  , lat:33.640441, long: -117.824051, description:"Vista Del Campo (also known as VDC) is a housing community owned by ACC apartments located on the east side of campus. It is home to undergraduate students (second year and above) and graduate students. VDC provides apartment style homes from 1 Bedroom to 4 Bedroom under lease agreements."},  //13
  { name:'Anteater Recreation Center (ARC)' , lat:33.643361, long: -117.827945, description:"The ARC is an indoor 2-floor gym facility equipped with state-of-the art equipment. It provides over 35 free exercise classes, CPR/First Aid classes, personal training and much more. It is home for all club sports and intramural sports every quarter."},  //14
  { name:'Middle Earth'                     , lat:33.64465 , long: -117.837548, description:"Middle Earth is a first year housing community inspired by J.R.R Tolkien’s Lord of the Rings. It has 24 residence halls with 45 to 75 residents and a live-in resident advisor per hall. The community also has a dining hall, music room, study rooms, and a housing office. There is currently construction in the community. "},  //15
  //David
  { name:'Infinity Fountain'                , lat:33.644684, long: -117.843529, description:"One of the \'fountains of knowledge\'. Infinity fountain the most important landmark to see in UCI. Inside its rectanglular shape, the water streams hit the center of the circle and create the the water spread that has the shape of infinity. The fountain symbolizes the infinite knowledges for students to obtain."},  //16
  { name:'Student Center'                   , lat:33.648811, long: -117.842411, description:"Student Center is where most of the organizational events held place. Students also like to eat and study in the cafeteria located on the third floor of the student centers. If you pay attention to the bell ring every hour, you might discover something special!" },  //17
  { name:'Brian Pellar Sculpture'           , lat:33.648461, long: -117.840836, description:"Located at the center of Chancellor's Rose Garden, Brian Pellar Sculpture is part of the series of progressive forms made by Brian Pellar. The sculpture has a shape of a half-naked man kneeling down." },  //18
  { name:'Laurel L. Wilkening Rose Garden'  , lat:33.648461, long: -117.840836, description:"Laurel L. Wilkening Rose Garden is a tiny garden located between flagpole and University Town center bridge. Laurel L. Wilkening was thirs female chancellor of UCI who helped ICI achieved America's top 50 research university. The garden is dedicated to her achievement and honor." },  //19
  { name:'UCI Flagpoles'                    , lat:33.648018, long: -117.840836, description:"UCI Flagpoles is the first place to see after acrossing the bridge from University Town Center. It is also the most common meet up points for student clubs and organizations. Be sure to follow the traffic light." },  //20

  { name:'Bren Events Center'               , lat:33.649411, long: -117.846964, picture: require('./Photos/stops/brencenter.png'), desc:'The Bren Events Center is home to a wide variety of events from sporting events to musical performance to exhibitions and much more. It provides exciting entertainment to thousands of fans each year. '},  //11
  { name:'Arroyo Vista'                     , lat:33.646854, long: -117.829043, picture: require('./Photos/stops/arroyovista.png'), desc:'Arroyo Vista (commonly referred to as AV) is a theme sponsored housing community that provides homes to undergraduates and transfer students. Each house has 16 to 34 residents living in double occupancy rooms. Academic, special theme houses and greek themed homes can be found in Arroyo Vista.'},  //12
  { name:'Vista Del Campo'                  , lat:33.640441, long: -117.824051, picture: require('./Photos/stops/vdc.png'), desc:'Vista Del Campo (also known as VDC) is a housing community owned by ACC apartments located on the east side of campus. It is home to undergraduate students (second year and above) and graduate students. VDC provides apartment style homes from 1 Bedroom to 4 Bedroom under lease agreements.'},  //13
  { name:'Anteater Recreation Center'       , lat:33.643361, long: -117.827945, picture: require('./Photos/stops/arc.png'), desc:'The ARC is an indoor 2-floor gym facility equipped with state-of-the art equipment. It provides over 35 free exercise classes, CPR/First Aid classes, personal training and much more. It is home for all club sports and intramural sports every quarter.'},  //14
  { name:'Middle Earth'                     , lat:33.64465 , long: -117.837548, picture: require('./Photos/stops/middleearth.png'), desc:'Middle Earth is a first year housing community inspired by J.R.R Tolkien’s Lord of the Rings. It has 24 residence halls with 45 to 75 residents and a live-in resident advisor per hall. The community also has a dining hall, music room, study rooms, and a housing office. There is currently construction in the community. '},  //15
];

export var TOUR_ROUTES =
[
  { name: 'Library'           ,route: [0,3,6]},                 //0
  { name: 'Residence Areas'   ,route: [0,10,12,13,15]},         //1
  { name: 'Social Area'       ,route: [0,1,9,11,14,17]},        //2
  { name: 'Landmarks'         ,route: [0,11,16,17,18,19,20]},   //3
]
